<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.vBeecEe' shared service.

return $this->privates['.service_locator.vBeecEe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\EmployeeController::create' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\EmployeeController::show' => ['privates', '.service_locator.ZN_dO1z', 'get_ServiceLocator_ZNDO1zService.php', true],
    'App\\Controller\\EmployeeController:create' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\EmployeeController:show' => ['privates', '.service_locator.ZN_dO1z', 'get_ServiceLocator_ZNDO1zService.php', true],
], [
    'App\\Controller\\EmployeeController::create' => '?',
    'App\\Controller\\EmployeeController::show' => '?',
    'App\\Controller\\EmployeeController:create' => '?',
    'App\\Controller\\EmployeeController:show' => '?',
]);
