<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXac7Xvb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXac7Xvb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXac7Xvb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXac7Xvb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXac7Xvb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Xac7Xvb',
    'container.build_id' => '0d83c45f',
    'container.build_time' => 1571173207,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXac7Xvb');
